# Generated by Django 3.2 on 2021-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfilemodel',
            name='file',
            field=models.FileField(default=True, null=True, upload_to=''),
        ),
    ]
