# Generated by Django 3.2 on 2021-05-08 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocBoardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('board_type', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JAVASCRIPT'), ('eS6', 'ES6'), ('node.js', 'NODE'), ('java', 'JAVA'), ('python', 'PYTHON'), ('sql', 'SQL'), ('react', 'REACT'), ('react-native', 'REACT-NATIVE'), ('firebase', 'FIREBASE'), ('graphql', 'GRAPHQL')], max_length=40)),
                ('description', models.TextField()),
                ('likeCount', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DOC_BOARDS',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_boards.docboardsmodel')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
    ]
